POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Example Person",
  "number": "040 1231234"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "",
  "number": "040 1231234"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Example",
  "number": ""
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Example Person",
  "number": "040 1231234"
}
